local Forgeframe = CreateFrame("Frame")
Forgeframe:RegisterEvent("PLAYER_ENTERING_WORLD")
Forgeframe:SetScript("OnEvent", function(initialLogin, ReloadUI)
    InitializeTalentTree()
    initializeItemTooltips()
    InitializePerks()
end)
